[config]
schemaVersion = "0.0.1"

[package]
namespace = "Trodi"
name = "BloodyRewards"
versionNumber = "1.0.5"
description = "Rewards System for VRising."
websiteUrl = "https://github.com/oscarpedrero/BloodyRewards"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"
deca-VampireCommandFramework = "0.9.0"
Trodi-BloodyCore = "2.0.0"
Trodi-BloodyWallet = "1.0.*"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["oakveil", "mods", "server"]